name: test-kikit
on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-kicad
      - name: Install dependencies and KiKit
        run: |
          sudo apt-get install --yes --no-install-recommends \
            zip inkscape make git libmagickwand-dev \
            libgraphicsmagick1-dev libmagickcore-dev \
            openscad bats
          sudo python -m pip install PcbDraw
          sudo python -m pip install -e .\[dev\]
      - run: make test
      - run: make doc
      - run: sudo make package

